server:
  port: 9000
  servlet:
    session:
      timeout: 24h

spring:
  application.name: oauth
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  servlet:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_SMTP_AUTH}
          timeout: ${EMAIL_SMTP_TIMEOUT}
          starttls:
            enable: ${EMAIL_SMTP_ENABLE}
management:
  info:
    git:
      mode: full
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    enabled: false
    sampling:
      probability: 1.0
springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: method

swagger:
  api-gateway-url: ${SWAGGER_URL}/${spring.application.name}

logout.redirect-url: ${SWAGGER_URL}

rsa:
  public-key: ${RSA_PUBLIC_KEY}
  private-key: ${RSA_PRIVATE_KEY}

file.upload.path: ${FILE_UPLOAD_PATH}

logging.level.org:
  springframework.security: trace
  hibernate.sql: debug